# Site settings
title: Anna Andolfatto, educatore cinofilo a Parma.
email: annaandolfatto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Anna Andolfatto lavora come educatore cinofilo a Parma e provincia, utilizza
  il metodo cognitivo zooantropologico e progetta l'attività di educazione con
  l'obiettivo di creare di rapporto speciale tra cane e proprietario, incentrato
  sulla fiducia reciproca e sulla collaborazione.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ditemifido.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty